#!/usr/bin/env node
"use strict";
/**
 * Security Tests -- C1: Secret Detection Bypass Resistance
 *
 * Tests the Gate engine's ability to detect secrets in tool inputs
 * (Bash commands, Edit/Write content) and resist bypass attempts.
 *
 * Gate handler: .claude/hooks/tobari-gate.js
 * Patterns tested: SECRET_PATTERNS, SENSITIVE_FILE_ACCESS_PATTERNS
 *
 * NOTE: All dummy secrets are constructed at RUNTIME via builder
 * functions using string concatenation, so the file itself does
 * not trigger git-guard or the gate's content scanning.
 *
 * Generated by: tests/_gen_c1.js
 */

const { describe, it, beforeEach, afterEach } = require("node:test");
const assert = require("node:assert/strict");
const path = require("node:path");
const fs = require("node:fs");

// Set CLAUDE_PROJECT_DIR before requiring modules
const PROJECT_DIR = path.resolve(__dirname, "..");
process.env.CLAUDE_PROJECT_DIR = PROJECT_DIR;

const tobariSession = require("../.claude/hooks/tobari-session.js");
const gate = require("../.claude/hooks/tobari-gate.js");

// --- Helpers ---

const SESSION_DIR = path.join(PROJECT_DIR, ".claude");
const SESSION_PATH = path.join(SESSION_DIR, "tobari-session.json");
let originalContent = null;

function saveSession(session) {
  fs.writeFileSync(SESSION_PATH, JSON.stringify(session, null, 2), "utf8");
  tobariSession._resetCache();
}

function restoreSession() {
  if (originalContent !== null) {
    fs.writeFileSync(SESSION_PATH, originalContent, "utf8");
  } else {
    try { fs.unlinkSync(SESSION_PATH); } catch {}
  }
  tobariSession._resetCache();
}

function makeBaseSession(overrides = {}) {
  return {
    active: true,
    task: "test-c1-secret",
    profile: "standard",
    started_at: "2026-03-08T00:00:00Z",
    gates_passed: ["STG0"],
    retry_count: 0,
    token_usage: { input: 0, output: 0, budget: 500000 },
    git_state: { branch: "test", uncommitted_changes: false, pr_url: null },
    contract: {
      intent: "security test",
      requirements: { do: ["test"], do_not: ["none"] },
      dod: ["all secret detection tests pass"],
      scope: {
        include: ["tests/", ".claude/hooks/"],
        exclude: [],
      },
      risk_level: "medium",
    },
    learned_permissions: [],
    evidence: [],
    ...overrides,
  };
}

function assertDeny(result, context) {
  assert.ok(result !== null, "Expected deny but got null -- " + context);
  assert.strictEqual(
    result.hookSpecificOutput.permissionDecision,
    "deny",
    "Expected permissionDecision=deny -- " + context,
  );
}

function assertAllow(result, context) {
  if (result === null) return;
  assert.notStrictEqual(
    result.hookSpecificOutput.permissionDecision,
    "deny",
    "Expected allow but got deny -- " + context,
  );
}


// --- Secret Builders (runtime-only assembly) ---

function buildApiKeyAssignment() {
  var kw = ["ap","i_","ke","y"].join("");
  var val = ["abcdefghij","klmnopqrst","uvwx"].join("");
  return kw + ' = "' + val + '"';
}

function buildApiKeyDashColon() {
  var kw = ["ap","i-","ke","y"].join("");
  var val = ["abcdefghij","klmnopqrst","uvwx"].join("");
  return kw + ': "' + val + '"';
}

function buildAwsKey() {
  return ["AK","IA"].join("") + "IOSFODNN7EXAMPLE";
}

function buildAwsKey2() {
  return ["AK","IA"].join("") + "IOSFODNN7EXAMPLE";
}

function buildPasswordAssignment() {
  var kw = ["pas","swo","rd"].join("");
  var val = ["SuperS","ecretP","ass123!"].join("");
  return kw + ' = "' + val + '"';
}

function buildPasswordUpper() {
  var kw = ["PAS","SWO","RD"].join("");
  var val = ["SomeP","assV","alue!xx"].join("");
  return kw + ' = "' + val + '"';
}

function buildSecretAssignment() {
  var kw = ["sec","re","t"].join("");
  var val = ["MyTop","Secr","etValue123"].join("");
  return kw + '="' + val + '"';
}

function buildPrivateKeyHeader() {
  return ["-----BEG","IN PRIV","ATE KEY","-----"].join("");
}

function buildRsaPrivateKeyHeader() {
  return ["-----BEG","IN RSA"," PRIV","ATE KEY","-----"].join("");
}

function buildPostgresConn() {
  return ["post","gres","://adm","in:s3cr","3tPass","@db.example.com:5432/mydb"].join("");
}

function buildMongoConn() {
  return ["mongo","db://","appuser",":myPas","sword@","mongo.example.com:27017/appdb"].join("");
}

function buildRedisConn() {
  return ["redi","s://","default",":r3dis","Pass@","redis.example.com:6379"].join("");
}

function buildMysqlConn() {
  return ["my","sql://","root:",  "dbPas","s123@","localhost:3306/myapp"].join("");
}


// ========================================================================
// Category 1: Direct Detection -- secrets that MUST be caught
// ========================================================================

describe("C1-1: Direct secret detection", () => {
  beforeEach(() => {
    try { originalContent = fs.readFileSync(SESSION_PATH, "utf8"); } catch { originalContent = null; }
    saveSession(makeBaseSession());
  });

  afterEach(() => {
    restoreSession();
  });

  it("detects API key assignment in Bash command", () => {
    var assignment = buildApiKeyAssignment();
    var command = "curl -H '" + assignment + "' https://example.com";

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command },
    });

    assertDeny(result, "API key in Bash command");
  });

  it("detects AWS access key in Edit content", () => {
    var awsKey = buildAwsKey();

    var result = gate.handler({
      tool_name: "Edit",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_config.py"),
        old_string: "placeholder",
        new_string: 'AWS_KEY = "' + awsKey + '"',
      },
    });

    assertDeny(result, "AWS access key in Edit content");
  });

  it("detects password assignment in Write content", () => {
    var content = "config = {\n  " + buildPasswordAssignment() + "\n}";

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_config.yaml"),
        content,
      },
    });

    assertDeny(result, "Password in Write content");
  });

  it("detects private key header in Write content", () => {
    var header = buildPrivateKeyHeader();
    var content = header + "\nMIIEvgIBADANBgkq\n-----END KEY-----";

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_key.pem"),
        content,
      },
    });

    assertDeny(result, "Private key header in Write content");
  });

  it("detects RSA private key header in Edit content", () => {
    var header = buildRsaPrivateKeyHeader();
    var content = header + "\nMIIEowIBAAKCAQEA\n-----END KEY-----";

    var result = gate.handler({
      tool_name: "Edit",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_rsa.pem"),
        old_string: "placeholder",
        new_string: content,
      },
    });

    assertDeny(result, "RSA private key header in Edit content");
  });

  it("detects Postgres connection string in Bash command", () => {
    var connStr = buildPostgresConn();
    var command = 'psql "' + connStr + '"';

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command },
    });

    assertDeny(result, "Connection string in Bash command");
  });

  it("detects MongoDB connection string in Write content", () => {
    var connStr = buildMongoConn();
    var content = 'const URI = "' + connStr + '";';

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_db_config.js"),
        content,
      },
    });

    assertDeny(result, "MongoDB connection string in Write content");
  });

  it("detects SSH key file access via cat", () => {
    var cmd = ["cat", " ~/.", "ssh/id_rsa"].join("");

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command: cmd },
    });

    assertDeny(result, "SSH key file access via cat");
  });

  it("detects AWS credentials file access via less", () => {
    var cmd = ["less", " ~/.", "aws/credentials"].join("");

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command: cmd },
    });

    assertDeny(result, "AWS credentials file access via less");
  });

  it("detects GnuPG key file access via tail", () => {
    var cmd = ["tail", " ~/.", "gnupg/secring.gpg"].join("");

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command: cmd },
    });

    assertDeny(result, "GnuPG key file access via tail");
  });

  it("detects /root SSH file access via head", () => {
    var cmd = ["head", " /root/.", "ssh/authorized_keys"].join("");

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command: cmd },
    });

    assertDeny(result, "SSH file access in /root via head");
  });

  it("detects .env file access via cat", () => {
    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command: "cat .env" },
    });

    assertDeny(result, ".env file access via cat");
  });

  it("detects Kubernetes config access via type", () => {
    var cmd = ["type", " ~/.", "kube/config"].join("");

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command: cmd },
    });

    assertDeny(result, "Kubernetes config access via type");
  });

  it("detects secret keyword assignment in Bash command", () => {
    var assignment = buildSecretAssignment();
    var command = "export " + assignment;

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command },
    });

    assertDeny(result, "secret keyword assignment in Bash command");
  });
});


// ========================================================================
// Category 2: Bypass Attempts -- test resistance to evasion techniques
// ========================================================================

describe("C1-2: Bypass attempt resistance", () => {
  beforeEach(() => {
    try { originalContent = fs.readFileSync(SESSION_PATH, "utf8"); } catch { originalContent = null; }
    saveSession(makeBaseSession());
  });

  afterEach(() => {
    restoreSession();
  });

  it("KNOWN GAP: base64-encoded secret is NOT detected by regex patterns", () => {
    // Base64-encoding a secret evades regex-based detection.
    // This test documents the known limitation.
    var parts = ["ap", "i_ke", "y='", "Real", "Secr", "etValue12345678'"];
    var b64 = Buffer.from(parts.join("")).toString("base64");
    var command = 'echo "' + b64 + '" | base64 -d';

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command },
    });

    // The base64 string does not match plaintext patterns.
    assertAllow(result, "Base64-encoded secret (known gap)");
  });

  it("detects API key with extra whitespace around separator", () => {
    var kw = ["ap", "i_", "ke", "y"].join("");
    var val = ["abcdefghij", "klmnopqrst", "uvwx"].join("");
    var content = kw + " =  \"" + val + "\"";

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_ws.py"),
        content,
      },
    });

    assertDeny(result, "API key with extra whitespace");
  });

  it("detects API key using colon separator", () => {
    var content = buildApiKeyDashColon();

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_colon.yaml"),
        content,
      },
    });

    assertDeny(result, "API key with colon separator");
  });

  it("detects PASSWORD (uppercase) assignment", () => {
    var content = buildPasswordUpper();

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_pw.conf"),
        content,
      },
    });

    assertDeny(result, "PASSWORD (uppercase) assignment");
  });

  it("hex-encoded value still matches when keyword is plaintext", () => {
    var hexVal = Buffer.from("SomeSecretValue!").toString("hex");
    var kw = ["pas", "swo", "rd"].join("");
    var content = kw + ' = "' + hexVal + '"';

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_hex.conf"),
        content,
      },
    });

    // hex chars are alphanumeric so [^"']{8,} matches
    assertDeny(result, "Hex-encoded value with plaintext keyword");
  });

  it("KNOWN GAP: unicode homoglyph in key prefix is NOT detected", () => {
    // Cyrillic small 'a' (U+0430) replaces Latin 'a'
    var val = ["abcdefghij", "klmnopqrst", "uvwx"].join("");
    // \u0430 = Cyrillic 'a' — regex uses ASCII, so won't match
    var content = "\u0430" + 'pi_key = "' + val + '"';

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_homoglyph.py"),
        content,
      },
    });

    assertAllow(result, "Unicode homoglyph bypass (known gap)");
  });

  it("detects Redis connection string in Bash command", () => {
    var connStr = buildRedisConn();
    var command = 'redis-cli -u "' + connStr + '"';

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command },
    });

    assertDeny(result, "Redis connection string in Bash command");
  });

  it("detects MySQL connection string in Write content", () => {
    var connStr = buildMysqlConn();
    var content = 'const DB_URL = "' + connStr + '";';

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_mysql.js"),
        content,
      },
    });

    assertDeny(result, "MySQL connection string in Write content");
  });

  it("detects AWS key embedded in larger text", () => {
    var awsKey = buildAwsKey2();
    var content = "config.aws_id = \"" + awsKey + "\"";

    var result = gate.handler({
      tool_name: "Edit",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_aws2.py"),
        old_string: "old",
        new_string: content,
      },
    });

    assertDeny(result, "AWS key embedded in config assignment");
  });

  it("detects secret buried in multiline content", () => {
    var assignment = buildApiKeyAssignment();
    var content = [
      "# Configuration file",
      "database_host = localhost",
      "database_port = 5432",
      assignment,
      "debug = false",
    ].join("\n");

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_multi.conf"),
        content,
      },
    });

    assertDeny(result, "Secret buried in multiline content");
  });
});


// ========================================================================
// Category 3: False Positive Avoidance -- should NOT be caught
// ========================================================================

describe("C1-3: False positive avoidance", () => {
  beforeEach(() => {
    try { originalContent = fs.readFileSync(SESSION_PATH, "utf8"); } catch { originalContent = null; }
    saveSession(makeBaseSession());
  });

  afterEach(() => {
    restoreSession();
  });

  it("allows normal Bash commands without secrets", () => {
    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command: "ls -la && echo hello" },
    });

    assertAllow(result, "Normal ls/echo command");
  });

  it("allows git commands without secrets", () => {
    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command: "git status && git log --oneline -5" },
    });

    assertAllow(result, "Normal git status/log command");
  });

  it("allows file operations without sensitive paths", () => {
    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command: "cat README.md" },
    });

    assertAllow(result, "cat README.md (not a sensitive file)");
  });

  it("allows documentation mentioning keyword without actual value", () => {
    var content = [
      "# Configuration Guide",
      "",
      "Set your key using environment variables:",
      "  export MY_KEY=$YOUR_KEY",
      "",
      "The key field is required for authentication.",
    ].join("\n");

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_docs.md"),
        content,
      },
    });

    assertAllow(result, "Documentation mentioning keyword without real value");
  });

  it("allows short password-like values under 8 chars", () => {
    // The pattern requires [^"']{8,} -- values under 8 chars pass
    var kw = ["pas", "swo", "rd"].join("");
    var content = kw + ' = "short"';

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_short_pw.conf"),
        content,
      },
    });

    assertAllow(result, "Password value under 8 chars (below threshold)");
  });

  it("allows placeholder tokens under 20 chars for API key pattern", () => {
    // Pattern requires [A-Za-z0-9_-]{20,} so 13 chars should NOT match
    var kw = ["ap", "i_", "ke", "y"].join("");
    var content = kw + ' = "YOUR_KEY_HERE"';

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_placeholder.conf"),
        content,
      },
    });

    assertAllow(result, "Placeholder token under 20 chars");
  });

  it("allows Write to scope-included path without secrets", () => {
    var content = "const x = 42;\nmodule.exports = { x };\n";

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_normal.js"),
        content,
      },
    });

    assertAllow(result, "Normal JS content without secrets");
  });

  it("allows Edit with safe content", () => {
    var result = gate.handler({
      tool_name: "Edit",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_edit.js"),
        old_string: "const a = 1;",
        new_string: "const a = 2;",
      },
    });

    assertAllow(result, "Simple numeric value change");
  });

  it("allows npm/node commands", () => {
    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command: "node --version && npm test" },
    });

    assertAllow(result, "node/npm commands");
  });

  it("allows test -f check on sensitive paths (not reading content)", () => {
    var cmd = ["test -f ~/.", "ssh/id_rsa && echo exists"].join("");

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command: cmd },
    });

    // test -f is not in the sensitive file access pattern list
    assertAllow(result, "test -f on SSH path (existence check only)");
  });
});


// ========================================================================
// Category 4: Veil-off behavior (advisory only, no blocking)
// ========================================================================

describe("C1-4: Veil-off behavior (advisory only, no blocking)", () => {
  beforeEach(() => {
    try { originalContent = fs.readFileSync(SESSION_PATH, "utf8"); } catch { originalContent = null; }
    saveSession(makeBaseSession({ active: false }));
  });

  afterEach(() => {
    restoreSession();
  });

  it("does NOT block secrets when veil is inactive", () => {
    var assignment = buildApiKeyAssignment();
    var command = "curl -H '" + assignment + "' https://example.com";

    var result = gate.handler({
      tool_name: "Bash",
      tool_input: { command },
    });

    // Veil off: advisory mode only checks destructive Bash, NOT secrets
    if (result !== null) {
      assert.notStrictEqual(
        result.hookSpecificOutput.permissionDecision,
        "deny",
        "Veil-off should not deny secrets (advisory only)",
      );
    }
  });

  it("does NOT block connection string when veil is inactive", () => {
    var connStr = buildPostgresConn();
    var content = 'DB_URL = "' + connStr + '"';

    var result = gate.handler({
      tool_name: "Write",
      tool_input: {
        file_path: path.join(PROJECT_DIR, "tests", "dummy_veiloff.conf"),
        content,
      },
    });

    // In advisory mode, Write only triggers design advisory, not secret check
    if (result !== null) {
      assert.notStrictEqual(
        result.hookSpecificOutput.permissionDecision,
        "deny",
        "Veil-off should not deny connection strings",
      );
    }
  });
});
